build:
    image: bradrydzewski/python:3.3
    commands:
        - sudo pip install -r requirements.txt
        - xvfb-run python manage.py test lists
    environment:
        - DB_NAME=postgres
		- DB_USER=postgres
		- DB_PASS=postgres
		- DB_SERVICE=postgres
		- DB_PORT=5432

