build:
    image: bradrydzewski/python:3.3
    commands:
        - source /home/ubuntu/virtualenv/python3.3/bin/activate
        - whoami
        - which python
        - python --version
        - echo $VIRTUAL_ENV
        - echo $PATH
        - env
        - sudo pip install -r requirements.txt
        - xvfb-run python manage.py test lists

