build:
    image: python:3.5-onbuild
    commands:
        - whoami
        - which python
        - python --version
        - echo $VIRTUAL_ENV
        - echo $PATH
        - env
        - pip install -r requirements.txt
        - python manage.py test lists

