build:
    image: bradrydzewski/python:3.3
    commands:
        - which python
        - python --version
        - sudo pip install -r requirements.txt
        - xvfb-run python manage.py test lists

